### ISSUE TITLE
Forcing External Web Client causes a black screen on start

### ISSUE THREAD

**Issue by reggermont** [jellyfin/jellyfin-media-player#714]
**Describe the bug**

Starting Jellyfin Media Player with `forceExternalWebclient=true` or with jellyfin-media-player>v1.11.0 triggers an infinite black screen after showing the Jellyfin logo

The last logs are showing the following

```log
[info] unknown @ 0 - JS: [ApiProvider] Could not get current user undefined
[info] unknown @ 0 - JS: serviceWorker registered
[info] unknown @ 0 - JS: [ConnectionRequired] not logged in, redirecting to login page [object Object]
[info] unknown @ 0 - JS: [viewContainer] tryRestoreView [object Object]
[info] unknown @ 0 - JS: Uncaught (in promise) ChunkLoadError: Loading chunk 93649 failed.
(error: https://[REDACTED]/web/session-login.753f05edd723ee338fed.chunk.js)
```

but nothing else happens than the black screen

**To Reproduce**

1. Run Jellyfin server version = 10.9.7 (dunno if error specific to this version)
2. Start Jellyfin Media Player with `forceExternalWebclient=true` or with jellyfin-media-player>v1.11.0

**Expected behavior**

Jellyfin Media Player starting correctly

**Desktop (please complete the following information):**

 - OS: Arch Linux x86_64
 - Version 6.9.6-arch1-1
 - Installation Method: AUR

**Additional context**

 Jellyfin server exposed behind a Traefik on another computer

Logs are also showing the following lines

```log
[debug] unknown @ 0 - Using web-client URL:  "file:////usr/share/jellyfinmediaplayer/web-client/desktop/index.html"
[debug] unknown @ 0 - "Using path for extension: /usr/share/jellyfinmediaplayer/web-client/extension/"
```

Trying to open the file shows this error in the console

```log
find-webclient.js:81 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'settings')
    at find-webclient.js:81:40
    at find-webclient.js:87:3
```

**Comment by solidsnake1298** [comment]
Also on 1.11.1, I am not able to navigate most of the UI.  I can bring up the dashboard, but the dashboard home is not accessible (blank page), but most of the other dashboard panels will load.  I can't view my libraries, but I can play anything that is in "next up" or "continue watching".

**Comment by reggermont** [comment]
Doesn't seem related as I can't even see the dashboard home. You should open an another issue

**Comment by solidsnake1298** [comment]
I was able to resolve this issue by going to Dashboard > Devices and deleting the session for JMP then logging back in on JMP.

**Comment by fatexs** [comment]
Possibly dublicate of https://github.com/jellyfin/jellyfin-media-player/issues/688

Can you try if deleting Jellyfin cache data also helps on linux?

**Comment by andrewrabert** [comment]
Closing as `forceExternalWebclient` is no longer an option in v2.0
